### ISSUE TITLE
Not working due to api change

### ISSUE THREAD

**Issue by Prunoideae** [mibmo/gelbooru-api#1]
Gelbooru now returns `@attributes` in the result, making deserialization fail.
```json
{"@attributes":{"limit":100,"offset":0,"count":6846222},"post":[{"id":7243775,"created_at":"Thu May 12 09:31:49 -0500 
```
```
JsonDeserialize(Error("invalid type: map, expected a sequence", line: 1, column: 1))
```

**Comment by mibmo** [comment]
Thanks for the report!

I see you've created your own fork with a fix (and async tests as well!); would you mind submitting your changes as a pull requests? :)

**Comment by mibmo** [comment]
Take a look at `v0.4.0`. I'd love to hear if it fixes all your issues. :)
